### ISSUE TITLE
Invalid convergence of ArrayArbitrary

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/simple-check#2]
To be analysed:

```
  2) ArrayArbitrary (seed: 1514074620775)
       array
         Should shrink removing unecessary entries in the array:

      AssertionError [ERR_ASSERTION]: Should shrink to counterexample [5,5]
      + expected - actual

       [
         [
           5
      -    0
           5
         ]
       ]
```

**Comment by dubzzz** [comment]
Still an issue with the latest version:

```
  1) ArrayArbitrary (seed: 1514076013615)
       array
         Should shrink removing unecessary entries in the array:

      AssertionError [ERR_ASSERTION]: Should shrink to counterexample [5,5]
      + expected - actual

       [
         [
           5
      -    0
           5
      -    0
         ]
       ]

      at Decorator._callFunc (node_modules\empower-core\lib\decorator.js:110:20)
      at Decorator.concreteAssert (node_modules\empower-core\lib\decorator.js:103:17)
      at Function.decoratedAssert [as deepEqual] (node_modules\empower-core\lib\decorate.js:51:30)
      at Context.it (test\e2e\arbitraries\ArrayArbitrary.spec.ts:25:20)
```
